version: "3"

services:
  php:
    image: php:fpm
    entrypoint: php -S 0.0.0.0:8000 index.html
    ports:
      - "8000:8000"
    volumes:
      - ./public:/var/www/html
  websocket:
    build: ./docker/websocket
    entrypoint: php ./websocket.php
    ports:
      - "8282:8282"
    volumes:
      - ./src:/var/www/html
