version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    networks:
      - default-network
  php:
    build: ./docker/php
    expose:
      - "8282"
    volumes:
      - ./src:/var/www/html
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
