version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default-network
  php:
    image: php:fpm
    volumes:
      - ./src:/src
    networks:
      - default-network

networks:
  default-network:
    driver: bridge